// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golangStudy/2.web/8.ent/ent/accounts"
	"golangStudy/2.web/8.ent/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountsUpdate is the builder for updating Accounts entities.
type AccountsUpdate struct {
	config
	hooks    []Hook
	mutation *AccountsMutation
}

// Where appends a list predicates to the AccountsUpdate builder.
func (au *AccountsUpdate) Where(ps ...predicate.Accounts) *AccountsUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetAccount sets the "account" field.
func (au *AccountsUpdate) SetAccount(s string) *AccountsUpdate {
	au.mutation.SetAccount(s)
	return au
}

// SetPwd sets the "pwd" field.
func (au *AccountsUpdate) SetPwd(s string) *AccountsUpdate {
	au.mutation.SetPwd(s)
	return au
}

// SetNickname sets the "nickname" field.
func (au *AccountsUpdate) SetNickname(s string) *AccountsUpdate {
	au.mutation.SetNickname(s)
	return au
}

// SetEmail sets the "email" field.
func (au *AccountsUpdate) SetEmail(s string) *AccountsUpdate {
	au.mutation.SetEmail(s)
	return au
}

// SetMobile sets the "mobile" field.
func (au *AccountsUpdate) SetMobile(s string) *AccountsUpdate {
	au.mutation.SetMobile(s)
	return au
}

// Mutation returns the AccountsMutation object of the builder.
func (au *AccountsUpdate) Mutation() *AccountsMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, AccountsMutation](ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountsUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountsUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountsUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AccountsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(accounts.Table, accounts.Columns, sqlgraph.NewFieldSpec(accounts.FieldID, field.TypeInt32))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Account(); ok {
		_spec.SetField(accounts.FieldAccount, field.TypeString, value)
	}
	if value, ok := au.mutation.Pwd(); ok {
		_spec.SetField(accounts.FieldPwd, field.TypeString, value)
	}
	if value, ok := au.mutation.Nickname(); ok {
		_spec.SetField(accounts.FieldNickname, field.TypeString, value)
	}
	if value, ok := au.mutation.Email(); ok {
		_spec.SetField(accounts.FieldEmail, field.TypeString, value)
	}
	if value, ok := au.mutation.Mobile(); ok {
		_spec.SetField(accounts.FieldMobile, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accounts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AccountsUpdateOne is the builder for updating a single Accounts entity.
type AccountsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountsMutation
}

// SetAccount sets the "account" field.
func (auo *AccountsUpdateOne) SetAccount(s string) *AccountsUpdateOne {
	auo.mutation.SetAccount(s)
	return auo
}

// SetPwd sets the "pwd" field.
func (auo *AccountsUpdateOne) SetPwd(s string) *AccountsUpdateOne {
	auo.mutation.SetPwd(s)
	return auo
}

// SetNickname sets the "nickname" field.
func (auo *AccountsUpdateOne) SetNickname(s string) *AccountsUpdateOne {
	auo.mutation.SetNickname(s)
	return auo
}

// SetEmail sets the "email" field.
func (auo *AccountsUpdateOne) SetEmail(s string) *AccountsUpdateOne {
	auo.mutation.SetEmail(s)
	return auo
}

// SetMobile sets the "mobile" field.
func (auo *AccountsUpdateOne) SetMobile(s string) *AccountsUpdateOne {
	auo.mutation.SetMobile(s)
	return auo
}

// Mutation returns the AccountsMutation object of the builder.
func (auo *AccountsUpdateOne) Mutation() *AccountsMutation {
	return auo.mutation
}

// Where appends a list predicates to the AccountsUpdate builder.
func (auo *AccountsUpdateOne) Where(ps ...predicate.Accounts) *AccountsUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountsUpdateOne) Select(field string, fields ...string) *AccountsUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Accounts entity.
func (auo *AccountsUpdateOne) Save(ctx context.Context) (*Accounts, error) {
	return withHooks[*Accounts, AccountsMutation](ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountsUpdateOne) SaveX(ctx context.Context) *Accounts {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountsUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountsUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AccountsUpdateOne) sqlSave(ctx context.Context) (_node *Accounts, err error) {
	_spec := sqlgraph.NewUpdateSpec(accounts.Table, accounts.Columns, sqlgraph.NewFieldSpec(accounts.FieldID, field.TypeInt32))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Accounts.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accounts.FieldID)
		for _, f := range fields {
			if !accounts.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accounts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Account(); ok {
		_spec.SetField(accounts.FieldAccount, field.TypeString, value)
	}
	if value, ok := auo.mutation.Pwd(); ok {
		_spec.SetField(accounts.FieldPwd, field.TypeString, value)
	}
	if value, ok := auo.mutation.Nickname(); ok {
		_spec.SetField(accounts.FieldNickname, field.TypeString, value)
	}
	if value, ok := auo.mutation.Email(); ok {
		_spec.SetField(accounts.FieldEmail, field.TypeString, value)
	}
	if value, ok := auo.mutation.Mobile(); ok {
		_spec.SetField(accounts.FieldMobile, field.TypeString, value)
	}
	_node = &Accounts{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accounts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
