// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golangStudy/2.web/8.ent/ent/accounts"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountsCreate is the builder for creating a Accounts entity.
type AccountsCreate struct {
	config
	mutation *AccountsMutation
	hooks    []Hook
}

// SetAccount sets the "account" field.
func (ac *AccountsCreate) SetAccount(s string) *AccountsCreate {
	ac.mutation.SetAccount(s)
	return ac
}

// SetPwd sets the "pwd" field.
func (ac *AccountsCreate) SetPwd(s string) *AccountsCreate {
	ac.mutation.SetPwd(s)
	return ac
}

// SetNickname sets the "nickname" field.
func (ac *AccountsCreate) SetNickname(s string) *AccountsCreate {
	ac.mutation.SetNickname(s)
	return ac
}

// SetEmail sets the "email" field.
func (ac *AccountsCreate) SetEmail(s string) *AccountsCreate {
	ac.mutation.SetEmail(s)
	return ac
}

// SetMobile sets the "mobile" field.
func (ac *AccountsCreate) SetMobile(s string) *AccountsCreate {
	ac.mutation.SetMobile(s)
	return ac
}

// SetID sets the "id" field.
func (ac *AccountsCreate) SetID(i int32) *AccountsCreate {
	ac.mutation.SetID(i)
	return ac
}

// Mutation returns the AccountsMutation object of the builder.
func (ac *AccountsCreate) Mutation() *AccountsMutation {
	return ac.mutation
}

// Save creates the Accounts in the database.
func (ac *AccountsCreate) Save(ctx context.Context) (*Accounts, error) {
	return withHooks[*Accounts, AccountsMutation](ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AccountsCreate) SaveX(ctx context.Context) *Accounts {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AccountsCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AccountsCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AccountsCreate) check() error {
	if _, ok := ac.mutation.Account(); !ok {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required field "Accounts.account"`)}
	}
	if _, ok := ac.mutation.Pwd(); !ok {
		return &ValidationError{Name: "pwd", err: errors.New(`ent: missing required field "Accounts.pwd"`)}
	}
	if _, ok := ac.mutation.Nickname(); !ok {
		return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "Accounts.nickname"`)}
	}
	if _, ok := ac.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Accounts.email"`)}
	}
	if _, ok := ac.mutation.Mobile(); !ok {
		return &ValidationError{Name: "mobile", err: errors.New(`ent: missing required field "Accounts.mobile"`)}
	}
	return nil
}

func (ac *AccountsCreate) sqlSave(ctx context.Context) (*Accounts, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int32(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AccountsCreate) createSpec() (*Accounts, *sqlgraph.CreateSpec) {
	var (
		_node = &Accounts{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(accounts.Table, sqlgraph.NewFieldSpec(accounts.FieldID, field.TypeInt32))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.Account(); ok {
		_spec.SetField(accounts.FieldAccount, field.TypeString, value)
		_node.Account = value
	}
	if value, ok := ac.mutation.Pwd(); ok {
		_spec.SetField(accounts.FieldPwd, field.TypeString, value)
		_node.Pwd = value
	}
	if value, ok := ac.mutation.Nickname(); ok {
		_spec.SetField(accounts.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := ac.mutation.Email(); ok {
		_spec.SetField(accounts.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := ac.mutation.Mobile(); ok {
		_spec.SetField(accounts.FieldMobile, field.TypeString, value)
		_node.Mobile = value
	}
	return _node, _spec
}

// AccountsCreateBulk is the builder for creating many Accounts entities in bulk.
type AccountsCreateBulk struct {
	config
	builders []*AccountsCreate
}

// Save creates the Accounts entities in the database.
func (acb *AccountsCreateBulk) Save(ctx context.Context) ([]*Accounts, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Accounts, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AccountsCreateBulk) SaveX(ctx context.Context) []*Accounts {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AccountsCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AccountsCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
