// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"golangStudy/2.web/8.ent/ent/cwebsite"
	"golangStudy/2.web/8.ent/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CWebsiteQuery is the builder for querying CWebsite entities.
type CWebsiteQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.CWebsite
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CWebsiteQuery builder.
func (cq *CWebsiteQuery) Where(ps ...predicate.CWebsite) *CWebsiteQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *CWebsiteQuery) Limit(limit int) *CWebsiteQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *CWebsiteQuery) Offset(offset int) *CWebsiteQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CWebsiteQuery) Unique(unique bool) *CWebsiteQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *CWebsiteQuery) Order(o ...OrderFunc) *CWebsiteQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// First returns the first CWebsite entity from the query.
// Returns a *NotFoundError when no CWebsite was found.
func (cq *CWebsiteQuery) First(ctx context.Context) (*CWebsite, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cwebsite.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CWebsiteQuery) FirstX(ctx context.Context) *CWebsite {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CWebsite ID from the query.
// Returns a *NotFoundError when no CWebsite ID was found.
func (cq *CWebsiteQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cwebsite.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CWebsiteQuery) FirstIDX(ctx context.Context) int64 {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CWebsite entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CWebsite entity is found.
// Returns a *NotFoundError when no CWebsite entities are found.
func (cq *CWebsiteQuery) Only(ctx context.Context) (*CWebsite, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cwebsite.Label}
	default:
		return nil, &NotSingularError{cwebsite.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CWebsiteQuery) OnlyX(ctx context.Context) *CWebsite {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CWebsite ID in the query.
// Returns a *NotSingularError when more than one CWebsite ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CWebsiteQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cwebsite.Label}
	default:
		err = &NotSingularError{cwebsite.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CWebsiteQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CWebsites.
func (cq *CWebsiteQuery) All(ctx context.Context) ([]*CWebsite, error) {
	ctx = setContextOp(ctx, cq.ctx, "All")
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CWebsite, *CWebsiteQuery]()
	return withInterceptors[[]*CWebsite](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *CWebsiteQuery) AllX(ctx context.Context) []*CWebsite {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CWebsite IDs.
func (cq *CWebsiteQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, "IDs")
	if err = cq.Select(cwebsite.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CWebsiteQuery) IDsX(ctx context.Context) []int64 {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CWebsiteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, "Count")
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*CWebsiteQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CWebsiteQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CWebsiteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, "Exist")
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CWebsiteQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CWebsiteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CWebsiteQuery) Clone() *CWebsiteQuery {
	if cq == nil {
		return nil
	}
	return &CWebsiteQuery{
		config:     cq.config,
		ctx:        cq.ctx.Clone(),
		order:      append([]OrderFunc{}, cq.order...),
		inters:     append([]Interceptor{}, cq.inters...),
		predicates: append([]predicate.CWebsite{}, cq.predicates...),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SortID int32 `json:"sort_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CWebsite.Query().
//		GroupBy(cwebsite.FieldSortID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (cq *CWebsiteQuery) GroupBy(field string, fields ...string) *CWebsiteGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CWebsiteGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = cwebsite.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SortID int32 `json:"sort_id,omitempty"`
//	}
//
//	client.CWebsite.Query().
//		Select(cwebsite.FieldSortID).
//		Scan(ctx, &v)
//
func (cq *CWebsiteQuery) Select(fields ...string) *CWebsiteSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &CWebsiteSelect{CWebsiteQuery: cq}
	sbuild.label = cwebsite.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CWebsiteSelect configured with the given aggregations.
func (cq *CWebsiteQuery) Aggregate(fns ...AggregateFunc) *CWebsiteSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *CWebsiteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !cwebsite.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CWebsiteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CWebsite, error) {
	var (
		nodes = []*CWebsite{}
		_spec = cq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CWebsite).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CWebsite{config: cq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cq *CWebsiteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CWebsiteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cwebsite.Table, cwebsite.Columns, sqlgraph.NewFieldSpec(cwebsite.FieldID, field.TypeInt64))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cwebsite.FieldID)
		for i := range fields {
			if fields[i] != cwebsite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CWebsiteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(cwebsite.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = cwebsite.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CWebsiteGroupBy is the group-by builder for CWebsite entities.
type CWebsiteGroupBy struct {
	selector
	build *CWebsiteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CWebsiteGroupBy) Aggregate(fns ...AggregateFunc) *CWebsiteGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *CWebsiteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, "GroupBy")
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CWebsiteQuery, *CWebsiteGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *CWebsiteGroupBy) sqlScan(ctx context.Context, root *CWebsiteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CWebsiteSelect is the builder for selecting fields of CWebsite entities.
type CWebsiteSelect struct {
	*CWebsiteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *CWebsiteSelect) Aggregate(fns ...AggregateFunc) *CWebsiteSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CWebsiteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, "Select")
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CWebsiteQuery, *CWebsiteSelect](ctx, cs.CWebsiteQuery, cs, cs.inters, v)
}

func (cs *CWebsiteSelect) sqlScan(ctx context.Context, root *CWebsiteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
