// Code generated by ent, DO NOT EDIT.

package ent

import (
	"golangStudy/2.web/8.ent/ent/cwebsite"
	"golangStudy/2.web/8.ent/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cwebsiteFields := schema.CWebsite{}.Fields()
	_ = cwebsiteFields
	// cwebsiteDescCreateTime is the schema descriptor for create_time field.
	cwebsiteDescCreateTime := cwebsiteFields[10].Descriptor()
	// cwebsite.DefaultCreateTime holds the default value on creation for the create_time field.
	cwebsite.DefaultCreateTime = cwebsiteDescCreateTime.Default.(func() time.Time)
	// cwebsiteDescModifyTime is the schema descriptor for modify_time field.
	cwebsiteDescModifyTime := cwebsiteFields[12].Descriptor()
	// cwebsite.DefaultModifyTime holds the default value on creation for the modify_time field.
	cwebsite.DefaultModifyTime = cwebsiteDescModifyTime.Default.(func() time.Time)
}
