// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Accounts is the predicate function for accounts builders.
type Accounts func(*sql.Selector)

// CWebsite is the predicate function for cwebsite builders.
type CWebsite func(*sql.Selector)

// Website is the predicate function for website builders.
type Website func(*sql.Selector)
