// Code generated by ent, DO NOT EDIT.

package website

const (
	// Label holds the string label denoting the website type in the database.
	Label = "website"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSortID holds the string denoting the sort_id field in the database.
	FieldSortID = "sort_id"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldWebsiteName holds the string denoting the website_name field in the database.
	FieldWebsiteName = "website_name"
	// FieldWebsiteIcon holds the string denoting the website_icon field in the database.
	FieldWebsiteIcon = "website_icon"
	// FieldWebsiteURL holds the string denoting the website_url field in the database.
	FieldWebsiteURL = "website_url"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreateID holds the string denoting the create_id field in the database.
	FieldCreateID = "create_id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldModifyID holds the string denoting the modify_id field in the database.
	FieldModifyID = "modify_id"
	// FieldModifyTime holds the string denoting the modify_time field in the database.
	FieldModifyTime = "modify_time"
	// Table holds the table name of the website in the database.
	Table = "website"
)

// Columns holds all SQL columns for website fields.
var Columns = []string{
	FieldID,
	FieldSortID,
	FieldCategory,
	FieldWebsiteName,
	FieldWebsiteIcon,
	FieldWebsiteURL,
	FieldSummary,
	FieldDescription,
	FieldCreateID,
	FieldCreateTime,
	FieldModifyID,
	FieldModifyTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
